from functions import *


# Ana çalışma
if __name__ == "__main__":
    automation = DeviceAutomation()
    automation.open_login_page()
    automation.driver.maximize_window()  # Tarayıcıyı tam ekranda aç
    automation.login()
    automation.navigate_to_devices()
    automation.device_connection_online()
    time.sleep(1)
    """
    automation.navigate_to_jobs()
    automation.start_new_job()
    automation.select_dashcamnet()
    automation.give_job_name("dashcam")
    time.sleep(1)
    automation.click_camera_checkbox()
    time.sleep(1)
    automation.click_device_checkbox()
    time.sleep(1)
    automation.start_now()
    time.sleep(10)
    automation.show_stream_details()
    time.sleep(4)
    automation.select_camera_checkbox()
    time.sleep(5)
    automation.click_select_button()
    time.sleep(5)
    automation.navigate_analytics_panel()
    automation.create_new_dashboard_collection()
    automation.fill_dashboard_details(collection_name="My New Dashboard3")
    time.sleep(2)
    automation.save_dashboard_collection()
    automation.press_ok()
    time.sleep(2)
    automation.click_dashboard()
    time.sleep(2)
    automation.click_new_dashboard()
    time.sleep(2)
    automation.name_new_dashboard("New dashboard")
    time.sleep(2)
    automation.save_dashboard()
    automation.new_press_ok()
    time.sleep(2)
    automation.click_dashboard_again()
    time.sleep(3)
    """
    automation.navigate_analytics_board()
    time.sleep(1)
    automation.select_first_inference_job()
    automation.edit_layout()
    time.sleep(1)
    automation.add_new_chart()
    automation.chart_name("test1613")
    time.sleep(2)
    automation.select_chart_distribution()
    time.sleep(2)
    automation.select_first_model_name()
    time.sleep(3)
